import './main-menu';
import './tabs';
import './hot-deals-banner';
import './hot-deals-product';
import './carousel-posts';
import './shopping-cart';
import './leave-page-modal';
import './brands-slider';
import './section-Gallery';
